leveling_profile:
  WEREWOLVES:
    - n_WEREWOLVES_3
    - n_WEREWOLVES_2
    - n_WEREWOLVES_1
  DUNG_3:
    - n_WEREWOLVES_3
    - n_WEREWOLVES_2
    - n_WEREWOLVES_1
    - n_POISON_BULL_FIGHTERS_1
    - n_DARK_KNIGHTS_2
    - n_DARK_KNIGHTS_1
  LT_6:
    - n_WEREWOLVES_3
    - n_WEREWOLVES_2
    - n_WEREWOLVES_1
    - n_POISON_BULL_FIGHTERS_1
    - n_DARK_KNIGHTS_2
    - n_DARK_KNIGHTS_1
    - n_DEATH_KNIGHTS_4
    - n_DEATH_KNIGHTS_3
    - n_DEATH_KNIGHTS_2
    - n_DEATH_KNIGHTS_1
  T1:
    - n_WEREWOLVES_3
    - n_WEREWOLVES_2
    - n_WEREWOLVES_1
    - n_POISON_BULL_FIGHTERS_1
    - n_DARK_KNIGHTS_2
    - n_DARK_KNIGHTS_1
    - n_DEATH_KNIGHTS_4
    - n_DEATH_KNIGHTS_3
    - n_DEATH_KNIGHTS_2
    - n_DEATH_KNIGHTS_1
    - n_MUTANTS_2
    - n_MUTANTS_1
    # - n_BLOODY_WOLVES_3
    # - n_BLOODY_WOLVES_2
    # - n_BLOODY_WOLVES_1
  K1:
    - n_WEREWOLVES_3
    - n_WEREWOLVES_2
    - n_WEREWOLVES_1
    - n_POISON_BULL_FIGHTERS_1
    - n_DARK_KNIGHTS_2
    - n_DARK_KNIGHTS_1
    - n_DEATH_KNIGHTS_4
    - n_DEATH_KNIGHTS_3
    - n_DEATH_KNIGHTS_2
    - n_DEATH_KNIGHTS_1
    - n_MUTANTS_2
    - n_MUTANTS_1
    - n_BLOODY_WOLVES_3
    - n_BLOODY_WOLVES_2
    - n_BLOODY_WOLVES_1
    - n_SPLINTER_WOLVES_3
    - n_SPLINTER_WOLVES_2
    - n_SPLINTER_WOLVES_1
  K2:
    - n_WEREWOLVES_3
    - n_WEREWOLVES_2
    - n_WEREWOLVES_1
    - n_POISON_BULL_FIGHTERS_1
    - n_DARK_KNIGHTS_2
    - n_DARK_KNIGHTS_1
    - n_DEATH_KNIGHTS_4
    - n_DEATH_KNIGHTS_3
    - n_DEATH_KNIGHTS_2
    - n_DEATH_KNIGHTS_1
    - n_MUTANTS_2
    - n_MUTANTS_1
    - n_BLOODY_WOLVES_3
    - n_BLOODY_WOLVES_2
    - n_BLOODY_WOLVES_1
    - n_SPLINTER_WOLVES_3
    - n_SPLINTER_WOLVES_2
    - n_SPLINTER_WOLVES_1
    - n_BLADE_HUNTERS_2
    - n_BLADE_HUNTERS_1
  CW:
    - n_BOW_SCOUTS_1
    - n_CWOLVES_2
    - n_CWOLVES_1
    - n_HAMMER_SCOUTS_6
    - n_HAMMER_SCOUTS_5
    - n_HAMMER_SCOUTS_4
    - n_HAMMER_SCOUTS_3
    - n_HAMMER_SCOUTS_2
    - n_HAMMER_SCOUTS_1
  ZERKS:
    - n_WEREWOLVES_3
    - n_WEREWOLVES_2
    - n_WEREWOLVES_1
    - n_POISON_BULL_FIGHTERS_1
    - n_DARK_KNIGHTS_2
    - n_DARK_KNIGHTS_1
    - n_THUNDER_LICHES_1
    - n_MUTANTS_2
    - n_MUTANTS_1
    - n_BLOODY_WOLVES_1
    - n_SPLINTER_WOLVES_3
    - n_SPLINTER_WOLVES_2
    - n_SPLINTER_WOLVES_1
    - n_BLADE_HUNTERS_2
    - n_BLADE_HUNTERS_1
    - n_BERSERKERS_3
    - n_BERSERKERS_2
    - n_BERSERKERS_1
  GENOCIDERS:
    - n_WEREWOLVES_3
    - n_WEREWOLVES_2
    - n_WEREWOLVES_1
    - n_POISON_BULL_FIGHTERS_1
    - n_DARK_KNIGHTS_2
    - n_DARK_KNIGHTS_1
    - n_THUNDER_LICHES_1
    - n_MUTANTS_2
    - n_MUTANTS_1
    - n_BLOODY_WOLVES_1
    - n_SPLINTER_WOLVES_3
    - n_SPLINTER_WOLVES_2
    - n_SPLINTER_WOLVES_1
    - n_BLADE_HUNTERS_2
    - n_BLADE_HUNTERS_1
    - n_BERSERKERS_3
    - n_BERSERKERS_2
    - n_BERSERKERS_1
    - n_GENOCIDERS_3
    - n_GENOCIDERS_2
    - n_GENOCIDERS_1
  CRYPTAS:
    - n_BOW_SCOUTS_1
    - n_CWOLVES_2
    - n_CWOLVES_1
    - n_HAMMER_SCOUTS_6
    - n_HAMMER_SCOUTS_5
    - n_HAMMER_SCOUTS_4
    - n_HAMMER_SCOUTS_3
    - n_HAMMER_SCOUTS_2
    - n_HAMMER_SCOUTS_1
    - n_BONE_SCORPIONS_4
    - n_BONE_SCORPIONS_3
    - n_BONE_SCORPIONS_2
    - n_BONE_SCORPIONS_1
    - n_ORCUSES_1
    - n_CRYPTAS_2
    - n_CRYPTAS_1
  QUEENS:
    - n_WEREWOLVES_3
    - n_WEREWOLVES_2
    - n_WEREWOLVES_1
    - n_POISON_BULL_FIGHTERS_1
    - n_DARK_KNIGHTS_2
    - n_DARK_KNIGHTS_1
    - n_THUNDER_LICHES_1
    - n_BLOODY_QUEENS_1
    - n_BLOODY_QUEENS_2
    - n_BLOODY_QUEENS_3
    - n_BLOODY_QUEENS_4
  CONDRAS:
    - n_WEREWOLVES_3
    - n_WEREWOLVES_2
    - n_WEREWOLVES_1
    - n_POISON_BULL_FIGHTERS_1
    - n_DARK_KNIGHTS_2
    - n_DARK_KNIGHTS_1
    - n_THUNDER_LICHES_1
    - n_MUTANTS_2
    - n_MUTANTS_1
    - n_BLOODY_WOLVES_1
    - n_SPLINTER_WOLVES_3
    - n_SPLINTER_WOLVES_2
    - n_SPLINTER_WOLVES_1
    - n_BLADE_HUNTERS_2
    - n_BLADE_HUNTERS_1
    - n_BERSERKERS_3
    - n_BERSERKERS_2
    - n_BERSERKERS_1
    - n_GENOCIDERS_3
    - n_GENOCIDERS_2
    - n_GENOCIDERS_1
    - n_CONDRAS_2
    - n_CONDRAS_1
stat_profile:
  SUMM_K1:
    agi: r1
    ene: r1
    str: f400
    vit: f1100
  SUMM_SWAMP:
    agi: r1
    ene: r1
    str: f400
    vit: f2100
  BK_130lv:
    agi: f13000
    ene: r1
    str: r2
    vit: f3000
  BK_START:
    agi: r2
    ene: r1
    str: r1
    vit: f100
  MG_START:
    agi: r3
    ene: f100
    str: r2
    vit: f200
  MG_TARKAN:
    agi: r2
    ene: f200
    str: r3
    vit: f600
  SM_K2:
    agi: r2
    ene: r3
    str: f400
    vit: f2600
  SM_K1:
    agi: r2
    ene: r3
    str: f400
    vit: f1100
  MG_ENE_110lv:
    str: f1500
    vit: f500
    agi: f17000
    ene: r1
  SUMM_96lv:
    str: f300
    vit: f700
    agi: f20000
    ene: r1